version: '3'

services:
  traefik:
    image: traefik:v1.7
    command: --api --docker
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  nginx:
    image: nginx:latest
    ports:
      - 80:80
  influxdb:
    image: quay.io/influxdb/influxdb:2.0.0-alpha
    ports:
      - 9999:9999
    labels:
      - "traefik.http.routers.influxdb.rule=Host('influx.localhost')"
